### ISSUE TITLE
"paramiko is not installed"

### ISSUE THREAD

**Issue by mcenirm** [mcenirm/docker-ansible#1]
Cannot SSH to target host because `paramiko` has a problem:

```
$ docker run --rm -it -v "$PWD":/playbooks -w /playbooks mcenirm/ansible ansible example -m setup
example | FAILED! => {
    "failed": true, 
    "msg": "paramiko is not installed"
}
$ docker run --rm -it -v "$PWD":/playbooks -w /playbooks mcenirm/ansible python -c 'import paramiko'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 32, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

**Comment by mcenirm** [comment]
According to http://stackoverflow.com/a/22148284 `pkg_resources` is from `setuptools`.

`setuptools` does not seem to be a dependency for `py2-paramiko`:

```
$ docker run --rm mcenirm/ansible apk info -a py2-paramiko
py2-paramiko-2.0.2-r2 depends on:
py2-crypto
py2-cryptography
py2-ecdsa
python2
$ docker run --rm mcenirm/ansible apk search setuptools
py-setuptools-29.0.1-r0
```
